title: Haymarket theme
description: A GitHub Pages theme to easily launch Chicago DSA websites.
chapter:
  name: Chicago DSA
  location: Chicago
  url: https://www.chicagodsa.org/
  facebook: ChicagoDemSocialists
  instagram: chicagodsa
  twitter: ChicagoCityDSA
google_analytics:
remote_theme: ChicagoDSA/haymarket
plugins:
  - jekyll-seo-tag

banner:
  text: "**Here's a banner:** you can enable, style, and link it"
  link: another-page
