title: Haymarket theme
description: A GitHub Pages theme to easily launch Chicago DSA websites.
chapter:
  name: Your DSA Chapter
  location: Your City
  url:
  facebook: "?"
  instagram: "?"
  twitter: "?"
custom-join: # Add custom join URL here
google_analytics:
permalink: pretty
remote_theme: ChicagoDSA/haymarket
plugins:
  - jekyll-seo-tag

# Leave empty to disable
banner:
  text: "**Here's a banner:** you can turn it off/on, add styling, and link to other pages"
  link: another-page

defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: default
      image: "assets/images/og-image.png"

# Add collections here
# https://jekyllrb.com/docs/collections/
collections:
  tiles:
    output: true
