title: Haymarket theme
description: A GitHub Pages theme to easily launch Chicago DSA websites.
chapter:
  name: Your DSA Chapter
  url:
  facebook: "?"
  instagram: "?"
  twitter: "?"
custom-join: # Add custom join URL here
google_analytics:
teamup: "cb7ef970fd2b7b1a85acd5a8a2ef6d7f77477648b0963c29c629391742f24c5a"
permalink: pretty

# Add content here to enable a site-wide, top banner
banner:
  text: "**Here's a banner:** you can turn it off/on, add styling, and link to other pages"
  link: another-page

# Set default front matter for Markdown files
defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: default
      image: "assets/images/og-image.png"

# Manage lists of content with collections
# https://jekyllrb.com/docs/collections/
collections:
  tiles:
    output: true
